name: Trunk Upload Dummy Impacted Targets
author: trunk.io
description: Trunk.io Github Action to Upload a Dummy, Non-Meaningful List of Impacted Targets

inputs:
  trunk-token:
    description: Repo API token used for authentication. Can be found at app.trunk.io.
    required: true
  target-branch:
    description:
      The Merge Instance's target branch. If unspecified, defaults to the repository's default
      branch.
    required: false
  verbose:
    description: Whether to enable verbose logging. Defaults to false.
    required: false

runs:
  using: composite
  steps:
    - name: Prerequisites
      id: prerequisites
      run: ${GITHUB_ACTION_PATH}/prerequisites.sh
      shell: bash
      env:
        TARGET_BRANCH: ${{ inputs.target-branch }}
        DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

    - name: Upload Dummy Impacted Targets
      run: ${GITHUB_ACTION_PATH}/upload_dummy_impacted_targets.sh
      shell: bash
      env:
        API_TOKEN: ${{ inputs.trunk-token }}
        REPOSITORY: ${{ github.repository }}
        TARGET_BRANCH: ${{ steps.prerequisites.outputs.merge_instance_branch }}
        PR_NUMBER: ${{ github.event.pull_request.head.sha }}
        PR_SHA: ${{ github.sha }}
