name: Upload Impacted Targets - bazel startup options
run-name: Upload Impacted Targets for ${{ github.ref_name }}
on: pull_request

jobs:
  compute_impacted_targets:
    name: Compute Impacted Targets (with startup options)
    if: startsWith(github.head_ref, 'impacted_targets_test/bazel_startup_options/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Compute Impacted Targets (with startup options)
        # trunk-ignore(semgrep/yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha)
        uses: trunk-io/merge-action@main
        with:
          trunk-token: ${{ secrets.TRUNK_REPO_API_TOKEN }}
          bazel-workspace-path: test_workspace
          verbose: 1
          bazel-startup-options: --host_jvm_args=-Xmx12G,--block_for_lock,--client_debug
        env:
          API_URL: https://api.trunk-staging.io:443/v1/setImpactedTargets
